name: Publish
on:
  workflow_run:
    workflows: [Lint]
    branches: [dev]
    types: [completed]
  
  push:
    branches:
      - "dev"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
         
      - name: Create a Pull Request for Release
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: release new version'
          title: 'Release new version'
          body: 'This PR contains the changes for the new release.'
          branch: 'release-${{ github.sha }}'  # Utilizza un nome di branch sicuro e semplice
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
